<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '',
  'Remark' => '',
  'Status' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => '感謝您的留言，我們將盡速回覆您的留言。',
  'Update Time' => '',
  'Address' => '聯絡地址',
  'Cellphone' => '市內電話',
  'Company' => '公司',
  'Contact' => '聯絡我們',
  'Contact|Contacts' => '聯絡我們',
  'Email' => 'E-Mail',
  'Fax' => '傳真號碼',
  'Firstname' => '姓氏',
  'Lastname' => '名字',
  'Message' => '留言',
  'Sex' => '稱謂',
  'Telephone' => '行動電話',
);
