<?php

/**
 * This is the model base class for the table "contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contact".
 *
 * Columns in table "contact" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $contact_id
 * @property string $name
 * @property string $gender
 * @property string $telphone
 * @property string $cellphone
 * @property string $fax
 * @property string $email
 * @property string $corporation
 * @property string $address
 * @property string $message
 * @property string $note
 * @property string $create_time
 * @property string $update_time
 *
 */
abstract class BaseContact extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contact';
	}

	public static function label($n = 1) {
		return Yii::t('M/contact', 'Contact|Contacts', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, gender, telphone, cellphone, fax, email, corporation, address, message, note', 'required'),
			array('name', 'length', 'max'=>32),
			array('gender, telphone, cellphone, fax', 'length', 'max'=>16),
			array('email', 'length', 'max'=>64),
			array('corporation, address', 'length', 'max'=>256),
			array('create_time, update_time', 'safe'),
			array('create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('contact_id, name, gender, telphone, cellphone, fax, email, corporation, address, message, note, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'contact_id' => Yii::t('M/contact', 'Contact'),
			'name' => Yii::t('M/contact', 'Name'),
			'gender' => Yii::t('M/contact', 'Gender'),
			'telphone' => Yii::t('M/contact', 'Telphone'),
			'cellphone' => Yii::t('M/contact', 'Cellphone'),
			'fax' => Yii::t('M/contact', 'Fax'),
			'email' => Yii::t('M/contact', 'Email'),
			'corporation' => Yii::t('M/contact', 'Corporation'),
			'address' => Yii::t('M/contact', 'Address'),
			'message' => Yii::t('M/contact', 'Message'),
			'note' => Yii::t('M/contact', 'Note'),
			'create_time' => Yii::t('M/contact', 'Create Time'),
			'update_time' => Yii::t('M/contact', 'Update Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('contact_id', $this->contact_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('telphone', $this->telphone, true);
		$criteria->compare('cellphone', $this->cellphone, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('corporation', $this->corporation, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);


		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'attributes'=>array(
					'*',
				),
			),
		));
	}

	public function behaviors() {
		return array(
			'CTimestampBehavior'=>array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'updateAttribute' => 'update_time',
				'createAttribute' => 'create_time',
				'setUpdateOnCreate' => true,
			),
        );
	}
}