<?php

/**
 * This is the model base class for the table "information".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Information".
 *
 * Columns in table "information" available as properties of the model,
 * followed by relations of table "information" available as properties of the model.
 *
 * @property integer $information_id
 * @property integer $parent_id
 * @property integer $sort_order
 * @property string $create_time
 * @property string $update_time
 *
 * @property Information $parent
 * @property Information[] $informations
 * @property InformationI18n $informationI18n
 * @property InformationI18n[] $informationI18ns
 */
abstract class BaseInformation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'information';
	}

	public static function label($n = 1) {
		return Yii::t('m/information', 'Information|Informations', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('parent_id, sort_order', 'numerical', 'integerOnly'=>true),
			array('create_time, update_time', 'safe'),
			array('parent_id, sort_order, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('information_id, parent_id, sort_order, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'parent' => array(self::BELONGS_TO, 'Information', 'parent_id'),
			'informations' => array(self::HAS_MANY, 'Information', 'parent_id'),
			'informationI18n' => array(self::HAS_ONE, 'InformationI18n', 'information_id', 'scopes' => array('t' => array())),
			'informationI18ns' => array(self::HAS_MANY, 'InformationI18n', 'information_id', 'index' => 'language_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'information_id' => Yii::t('m/information', 'Information'),
			'parent_id' => null,
			'sort_order' => Yii::t('m/information', 'Sort Order'),
			'create_time' => Yii::t('m/information', 'Create Time'),
			'update_time' => Yii::t('m/information', 'Update Time'),
			'parent' => null,
			'informations' => null,
			'informationI18ns' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('information_id', $this->information_id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('sort_order', $this->sort_order);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}