<?php

/**
 * This is the model base class for the table "contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contact".
 *
 * Columns in table "contact" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $contact_id
 * @property integer $status
 * @property string $firstname
 * @property string $lastname
 * @property integer $sex
 * @property string $telephone
 * @property string $cellphone
 * @property string $fax
 * @property string $email
 * @property string $company
 * @property string $address
 * @property string $message
 * @property string $remark
 * @property string $create_time
 * @property string $update_time
 *
 */
abstract class BaseContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contact';
	}

	public static function label($n = 1) {
		return Yii::t('m/contact', 'Contact|Contacts', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('firstname, lastname, telephone, email', 'required'),
			array('status, sex', 'numerical', 'integerOnly'=>true),
			array('firstname, lastname', 'length', 'max'=>32),
			array('telephone, cellphone, fax', 'length', 'max'=>16),
			array('email', 'length', 'max'=>64),
			array('company, address', 'length', 'max'=>256),
			array('message, remark, create_time, update_time', 'safe'),
			array('status, sex, cellphone, fax, company, address, message, remark, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('contact_id, status, firstname, lastname, sex, telephone, cellphone, fax, email, company, address, message, remark, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'contact_id' => Yii::t('m/contact', 'Contact'),
			'status' => Yii::t('m/contact', 'Status'),
			'firstname' => Yii::t('m/contact', 'Firstname'),
			'lastname' => Yii::t('m/contact', 'Lastname'),
			'sex' => Yii::t('m/contact', 'Sex'),
			'telephone' => Yii::t('m/contact', 'Telephone'),
			'cellphone' => Yii::t('m/contact', 'Cellphone'),
			'fax' => Yii::t('m/contact', 'Fax'),
			'email' => Yii::t('m/contact', 'Email'),
			'company' => Yii::t('m/contact', 'Company'),
			'address' => Yii::t('m/contact', 'Address'),
			'message' => Yii::t('m/contact', 'Message'),
			'remark' => Yii::t('m/contact', 'Remark'),
			'create_time' => Yii::t('m/contact', 'Create Time'),
			'update_time' => Yii::t('m/contact', 'Update Time'),
		);
	}
}