<?php

/**
 * This is the model base class for the table "product_image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductImage".
 *
 * Columns in table "product_image" available as properties of the model,
 * followed by relations of table "product_image" available as properties of the model.
 *
 * @property integer $product_image_id
 * @property integer $product_id
 * @property string $pic
 *
 * @property Product $product
 */
abstract class BaseProductImage extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'product_image';
	}

	public static function label($n = 1) {
		return Yii::t('m/productimage', 'ProductImage|ProductImages', $n);
	}

	public static function representingColumn() {
		return 'pic';
	}

	public function rules() {
		return array(
			array('product_id, pic', 'required'),
			array('product_id', 'numerical', 'integerOnly'=>true),
			array('pic', 'length', 'max'=>256),
			array('product_image_id, product_id, pic', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product_image_id' => Yii::t('m/productimage', 'Product Image'),
			'product_id' => null,
			'pic' => Yii::t('m/productimage', 'Pic'),
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('t.product_image_id', $this->product_image_id);
		$criteria->compare('t.product_id', $this->product_id);
		$criteria->compare('t.pic', $this->pic, true);


		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'defaultOrder' => 't.product_image_id ASC',
				'multiSort'=>true,
				'attributes'=>array(
					'*',
				),
			),
			'pagination' => array(
				'pageSize' => Yii::app()->request->getParam('pageSize', 10),
				'pageVar' => 'page',
			),
		));
	}

	public function behaviors() {
		return array(
			'CTimestampBehavior'=>array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'updateAttribute' => null,
                'createAttribute' => null,
				'setUpdateOnCreate' => true,
			),
        );
	}
}