<?php

/**
 * This is the model base class for the table "picture_i18n".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PictureI18n".
 *
 * Columns in table "picture_i18n" available as properties of the model,
 * followed by relations of table "picture_i18n" available as properties of the model.
 *
 * @property integer $picture_i18n_id
 * @property integer $picture_id
 * @property integer $language_id
 * @property integer $status
 * @property string $url
 * @property string $title
 * @property string $keywords
 * @property string $description
 *
 * @property Picture $picture
 * @property Language $language
 */
abstract class BasePictureI18n extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'picture_i18n';
	}

	public static function label($n = 1) {
		return Yii::t('m/picturei18n', 'PictureI18n|PictureI18ns', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('picture_id, language_id', 'required'),
			array('picture_id, language_id, status', 'numerical', 'integerOnly'=>true),
			array('url, title', 'length', 'max'=>256),
			array('keywords, description', 'safe'),
			array('status, url, title, keywords, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('picture_i18n_id, picture_id, language_id, status, url, title, keywords, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'picture' => array(self::BELONGS_TO, 'Picture', 'picture_id'),
			'language' => array(self::BELONGS_TO, 'Language', 'language_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'picture_i18n_id' => Yii::t('m/pictureI18n', 'Picture I18n'),
			'picture_id' => null,
			'language_id' => null,
			'status' => Yii::t('m/pictureI18n', 'Status'),
			'url' => Yii::t('m/pictureI18n', 'Url'),
			'title' => Yii::t('m/pictureI18n', 'Title'),
			'keywords' => Yii::t('m/pictureI18n', 'Keywords'),
			'description' => Yii::t('m/pictureI18n', 'Description'),
			'picture' => null,
			'language' => null,
		);
	}

	public function search() {
		$alias = $this->tableAlias;

		$criteria = new CDbCriteria;

		$criteria->compare("{$alias}.picture_i18n_id", $this->picture_i18n_id);
		$criteria->compare("{$alias}.picture_id", $this->picture_id);
		$criteria->compare("{$alias}.language_id", $this->language_id);
		$criteria->compare("{$alias}.status", $this->status);
		$criteria->compare("{$alias}.url", $this->url, true);
		$criteria->compare("{$alias}.title", $this->title, true);
		$criteria->compare("{$alias}.keywords", $this->keywords, true);
		$criteria->compare("{$alias}.description", $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}