<?php

/**
 * This is the model base class for the table "twzip_city".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TwzipCity".
 *
 * Columns in table "twzip_city" available as properties of the model,
 * followed by relations of table "twzip_city" available as properties of the model.
 *
 * @property integer $twzip_city_id
 * @property integer $sort_order
 * @property string $name
 *
 * @property TwzipCounty[] $twzipCounties
 */
abstract class BaseTwzipCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'twzip_city';
	}

	public static function label($n = 1) {
		return Yii::t('m/twzipcity', 'TwzipCity|TwzipCities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('sort_order', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('sort_order', 'default', 'setOnEmpty' => true, 'value' => null),
			array('twzip_city_id, sort_order, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'twzipCounties' => array(self::HAS_MANY, 'TwzipCounty', 'twzip_city_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'twzip_city_id' => Yii::t('m/twzipcity', 'Twzip City'),
			'sort_order' => Yii::t('m/twzipcity', 'Sort Order'),
			'name' => Yii::t('m/twzipcity', 'Name'),
			'twzipCounties' => null,
		);
	}

	public function search() {
		$alias = $this->tableAlias;

		$criteria = new CDbCriteria;

		$criteria->compare("{$alias}.twzip_city_id", $this->twzip_city_id);
		$criteria->compare("{$alias}.sort_order", $this->sort_order);
		$criteria->compare("{$alias}.name", $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}