<?php

/**
 * This is the model base class for the table "news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "News".
 *
 * Columns in table "news" available as properties of the model,
 * followed by relations of table "news" available as properties of the model.
 *
 * @property integer $news_id
 * @property integer $top
 * @property integer $sort_order
 * @property string $date_added
 * @property string $create_time
 * @property string $update_time
 *
 * @property NewsI18n $newsI18n
 * @property NewsI18n[] $newsI18ns
 */
abstract class BaseNews extends GxActiveRecord {

	public $filterI18n;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news';
	}

	public static function label($n = 1) {
		return Yii::t('m/news', 'News|News', $n);
	}

	public static function representingColumn() {
		return 'date_added';
	}

	public function rules() {
		return array(
			array('top, sort_order', 'numerical', 'integerOnly'=>true),
			array('date_added, create_time, update_time', 'safe'),
			array('top, sort_order, date_added, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('news_id, top, sort_order, date_added, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'newsI18n' => array(self::HAS_ONE, 'NewsI18n', 'news_id', 'scopes' => array('t' => array())),
			'newsI18ns' => array(self::HAS_MANY, 'NewsI18n', 'news_id', 'index' => 'language_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'news_id' => Yii::t('m/news', 'News'),
			'top' => Yii::t('m/news', 'Top'),
			'sort_order' => Yii::t('m/news', 'Sort Order'),
			'date_added' => Yii::t('m/news', 'Date Added'),
			'create_time' => Yii::t('m/news', 'Create Time'),
			'update_time' => Yii::t('m/news', 'Update Time'),
			'newsI18ns' => null,
		);
	}

	public function search() {
		$alias = $this->tableAlias;
	
		$criteria = new CDbCriteria;

		$criteria->compare("{$alias}.news_id", $this->news_id);
		$criteria->compare("{$alias}.top", $this->top);
		$criteria->compare("{$alias}.sort_order", $this->sort_order);
		$criteria->compare("{$alias}.date_added", $this->date_added, true);
		$criteria->compare("{$alias}.create_time", $this->create_time, true);
		$criteria->compare("{$alias}.update_time", $this->update_time, true);

		$criteria->with = array('newsI18ns');
		$criteria->group = "{$alias}.news_id";
		$criteria->together = true;

		$criteria->compare('newsI18ns.status', $this->filterI18n->status);
		$criteria->compare('newsI18ns.pic', $this->filterI18n->pic, true);
		$criteria->compare('newsI18ns.title', $this->filterI18n->title, true);
		$criteria->compare('newsI18ns.keywords', $this->filterI18n->keywords, true);
		$criteria->compare('newsI18ns.description', $this->filterI18n->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'defaultOrder' => "{$alias}.sort_order DESC, {$alias}.news_id ASC",
				'multiSort'=>true,
				'attributes'=>array(
					'sort_order'=>array(
						'desc'=>"{$alias}.sort_order DESC",
						'asc'=>"{$alias}.sort_order ASC",
					),
					'*',
				),
			),
			'pagination' => array(
				'pageSize' => Yii::app()->request->getParam('pageSize', 10),
				'pageVar' => 'page',
			),
		));
	}

	public function behaviors() {
		return array(
			'CTimestampBehavior'=>array(
				'class' => 'zii.behaviors.CTimestampBehavior',
				'updateAttribute' => 'update_time',
				'createAttribute' => 'create_time',
				'setUpdateOnCreate' => true,
			),
        );
	}
}