<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<br/>Welcome to <a href="{baseUrl}">{app}</a>.<br/><br/>Now, you can activate your account by clicking the following link:<br/><br/><a href="{link}">{link}</a><br/><br/>' => '',
  'Commition Failure' => '',
  'Contact Us' => '',
  'Female' => '',
  'List' => '',
  'Male' => '',
  'Please check your email: {email} to activate your account before login' => '',
  'Register' => '',
  'Sorry, failed to activate your account! Contact us if you have any question.' => '',
  'The page will redirect in {t} seconds' => '',
  'Validation Failure' => '',
  'You have updated your profile successfully .' => '',
  'Your account: {username} has been activated successfully !' => '',
  'Congratulations! You have successfully created your Yii application.' => '您已經成功創建第一個YII應用，祝賀您！',
  'Verification Code' => '驗證碼',
);
