<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Files' => '项目',
  'Price Formatter Is Incorrect' => '价格不正确',
  'Advanced Search' => '高级搜寻',
  'All' => '全部',
  'Cancel' => '取消',
  'Commition Failure' => '失败：提交资料失败',
  'Confirm Gallery Image Delete?' => '确认删除项目？',
  'Confirm Grid View Delete?' => '确定要删除选中项目吗？',
  'Confirm Grid View Update?' => '确定要送出编辑项目吗？',
  'Create' => '新增',
  'Delete' => '删除',
  'Design Team' => '元伸网页设计',
  'Female' => '女生',
  'Gallery Image Delete' => '删除',
  'Grid Actions' => '操作',
  'Items Should Be At Least One' => '项目需保留至少一个',
  'List' => '列表',
  'Login' => '登录',
  'Male' => '男生',
  'No' => '否',
  'No Results Found' => '没有选中的项目',
  'None' => ' - 无 - ',
  'Noticed' => '已阅读',
  'Operation' => '操作',
  'Operation Failure' => '失败：操作失败',
  'Operation Failure Including SubItems' => '失败：项目包含子项目',
  'Operation Success' => '成功：操作成功',
  'Parent_id can not be self or children' => '上级分类不能是自身或其子分类',
  'Save' => '送出',
  'Search' => '搜寻',
  'Select A Image' => '选择图片',
  'Tabs Basic' => '基本设置',
  'Tabs Image' => '产品多图',
  'Unnoticed' => '未阅读',
  'Update' => '编辑',
  'Upload Failure' => '文件上传失败',
  'Upload Successfully' => '文件上传成功',
  'Validation Failure' => '失败：操作失败，请检查栏位设置',
  'Welcome to administration panel:' => '您已登录為：',
  'Yes' => '是',
  'Your request is invalid.' => '您的请求无效。',
);
