<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Failed To Crop Image' => '图片剪裁失败',
  'Image File Can Not Be Detected' => '无法取得原图片信息',
  'Image File Is Not Found' => '无法找到原图片',
  'Image Parameters Is Incorrect' => '图片剪裁变数不正确',
  'Image Scale Can Not Be Calculate' => '无法计算图片比例',
);
