<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Customer' => '会员',
  'CustomerType' => '群组',
  'Customers' => '会员管理',
  'Account' => '帐号设定',
  'Admin' => '管理员',
  'Asset' => '缓存管理',
  'Catalog' => '产品管理',
  'Category' => '分类',
  'Contact' => '联络我们',
  'Dashboard' => '管理首页',
  'Exit System' => '退出系统',
  'Information' => '单页讯息',
  'News' => '最新消息',
  'Picture' => '图片管理',
  'Product' => '产品',
  'Setting' => '网站设定',
  'Site Frontend' => '网站首页',
  'System' => '系统设定',
);
