<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Analysis Google' => 'Google代码',
  'Mail Email Contact' => '联络我们',
  'Mail Smtp Host' => '服务器',
  'Mail Smtp Password' => '密码',
  'Mail Smtp Port' => '端口',
  'Mail Smtp User' => '帐号',
  'Meta Description' => '描述',
  'Meta Keywords' => '关键词',
  'Meta Title' => '网站名称',
  'Analysis' => '流量分析',
  'Mail' => '邮件主机',
  'Mail Email' => '邮箱',
  'Mail Smtp' => '主机',
  'Meta' => '搜寻优化',
  'Setting' => '设置',
  'Update' => '更新',
  'Asset Manager' => '缓存管理',
);
