<?php

/**
 * This is the model base class for the table "twzip_county".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TwzipCounty".
 *
 * Columns in table "twzip_county" available as properties of the model,
 * followed by relations of table "twzip_county" available as properties of the model.
 *
 * @property integer $twzip_county_id
 * @property integer $twzip_city_id
 * @property integer $sort_order
 * @property string $postcode
 * @property string $name
 *
 * @property TwzipCity $twzipCity
 */
abstract class BaseTwzipCounty extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'twzip_county';
	}

	public static function label($n = 1) {
		return Yii::t('m/twzipcounty', 'TwzipCounty|TwzipCounties', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('twzip_city_id, name', 'required'),
			array('twzip_city_id, sort_order', 'numerical', 'integerOnly'=>true),
			array('postcode', 'length', 'max'=>32),
			array('name', 'length', 'max'=>128),
			array('sort_order, postcode', 'default', 'setOnEmpty' => true, 'value' => null),
			array('twzip_county_id, twzip_city_id, sort_order, postcode, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'twzipCity' => array(self::BELONGS_TO, 'TwzipCity', 'twzip_city_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'twzip_county_id' => Yii::t('m/twzipCounty', 'Twzip County'),
			'twzip_city_id' => null,
			'sort_order' => Yii::t('m/twzipCounty', 'Sort Order'),
			'postcode' => Yii::t('m/twzipCounty', 'Postcode'),
			'name' => Yii::t('m/twzipCounty', 'Name'),
			'twzipCity' => null,
		);
	}

	public function search() {
		$alias = $this->tableAlias;

		$criteria = new CDbCriteria;

		$criteria->compare("{$alias}.twzip_county_id", $this->twzip_county_id);
		$criteria->compare("{$alias}.twzip_city_id", $this->twzip_city_id);
		$criteria->compare("{$alias}.sort_order", $this->sort_order);
		$criteria->compare("{$alias}.postcode", $this->postcode, true);
		$criteria->compare("{$alias}.name", $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}