<?php

/**
 * This is the model base class for the table "customer_group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CustomerGroup".
 *
 * Columns in table "customer_group" available as properties of the model,
 * followed by relations of table "customer_group" available as properties of the model.
 *
 * @property integer $customer_group_id
 * @property string $name
 * @property integer $default
 *
 * @property Customer[] $customers
 */
abstract class BaseCustomerGroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'customer_group';
	}

	public static function label($n = 1) {
		return Yii::t('m/customergroup', 'CustomerGroup|CustomerGroups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('default', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>32),
			array('default', 'default', 'setOnEmpty' => true, 'value' => null),
			array('customer_group_id, name, default', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'customers' => array(self::HAS_MANY, 'Customer', 'customer_group_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'customer_group_id' => Yii::t('m/customergroup', 'Customer Group'),
			'name' => Yii::t('m/customergroup', 'Name'),
			'default' => Yii::t('m/customergroup', 'Default'),
			'customers' => null,
		);
	}

	public function search() {
		$alias = $this->tableAlias;

		$criteria = new CDbCriteria;

		$criteria->compare("{$alias}.customer_group_id", $this->customer_group_id);
		$criteria->compare("{$alias}.name", $this->name, true);
		$criteria->compare("{$alias}.default", $this->default);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}