<?php

/**
 * This is the model base class for the table "product2image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Product2image".
 *
 * Columns in table "product2image" available as properties of the model,
 * followed by relations of table "product2image" available as properties of the model.
 *
 * @property integer $product2image_id
 * @property integer $product_id
 * @property string $pic
 *
 * @property Product $product
 */
abstract class BaseProduct2image extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'product2image';
	}

	public static function label($n = 1) {
		return Yii::t('M/product2image', 'Product2image|Product2images', $n);
	}

	public static function representingColumn() {
		return 'pic';
	}

	public function rules() {
		return array(
			array('product_id, pic', 'required'),
			array('product_id', 'numerical', 'integerOnly'=>true),
			array('pic', 'length', 'max'=>256),
			array('product2image_id, product_id, pic', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product2image_id' => Yii::t('M/product2image', 'Product2image'),
			'product_id' => null,
			'pic' => Yii::t('M/product2image', 'Pic'),
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('product2image_id', $this->product2image_id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('pic', $this->pic, true);


		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
				'attributes'=>array(
					'*',
				),
			),
		));
	}

}