<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Commition Failure' => '',
  'Operation Failure Including Items.' => '',
  'Operation Failure Including SubItems' => '',
  'Operation Failure.' => '',
  'Select A Image' => '',
  'Advanced Search' => '高級搜索',
  'All' => '全部',
  'Cancel' => '取消',
  'Confirm Delete Language?' => '警告：

您正在嘗試刪除語言。

這個操作將刪除關聯語言的所有資料。

確定要刪除語言項目嗎？',
  'Confirm Gallery Image Delete?' => '確認刪除項目？',
  'Confirm Grid View Delete?' => '確定要刪除選中項目嗎？',
  'Confirm Grid View Update?' => '確定要送出編輯項目嗎？',
  'Create' => '新增',
  'Delete' => '刪除',
  'Design Team' => '元伸網頁設計',
  'Female' => '女生',
  'Gallery Image Delete' => '刪除',
  'Grid Actions' => '操作',
  'List' => '列表',
  'Login' => '登錄',
  'Male' => '男生',
  'No' => '否',
  'No results found.' => '沒有選中的項目',
  'None' => ' - 無 - ',
  'Noticed' => '已閱讀',
  'Operation' => '操作',
  'Operation Failure' => '失敗：操作失敗',
  'Operation Success' => '成功：操作成功',
  'Product Images' => '商品圖片',
  'Save' => '送出',
  'Search' => '搜索',
  'Tabs Basic' => '基本設置',
  'Unnoticed' => '未閱讀',
  'Update' => '編輯',
  'Upload Successfully' => '文件上傳成功',
  'Validation Failure' => '失敗：操作失敗，請檢查欄位設置',
  'Welcome to administration panel:' => '您已登錄為：',
  'Yes' => '是',
  'Your request is invalid.' => '您的請求無效。',
);
