<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Advanced Search' => '高級搜索',
  'All' => '全部',
  'Cancel' => '取消',
  'Confirm Grid View Delete?' => '確定要刪除選中項目嗎？',
  'Create' => '新增',
  'Delete' => '刪除',
  'Design Team' => '元伸網頁設計',
  'Grid Actions' => '操作',
  'Grid View Delete' => '刪除',
  'List' => '列表',
  'Login' => '登錄',
  'No' => '否',
  'No results found.' => '沒有選中的項目',
  'None' => ' - 無 - ',
  'Operation Success' => '成功：操作成功',
  'Product Images' => '商品圖片',
  'Save' => '送出',
  'Search' => '搜索',
  'Sub Categories' => '分類',
  'Tabs Basic' => '基本設置',
  'Update' => '編輯',
  'Upload Successfully' => '文件上傳成功',
  'View' => '查看',
  'Welcome to administration panel:' => '您已登錄為：',
  'Yes' => '是',
  'Your request is invalid.' => '您的請求無效。',
);
