<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Failed To Crop Image' => '圖片剪裁失敗',
  'Image File Can Not Be Detected' => '無法取得原圖片信息',
  'Image File Is Not Found' => '無法找到原圖片',
  'Image Parameters Is Incorrect' => '圖片剪裁變數不正確',
  'Image Scale Can Not Be Calculate' => '無法計算圖片比例',
);
