<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Error Page' => '系統提示',
  'Error' => '錯誤',
  'Error403' => '錯誤403',
  'Error403 Message' => '您沒有權限訪問這個頁面',
  'Error404' => '錯誤404',
  'Error404 Message' => '您請求訪問的頁面沒有找到',
  'Error500' => '錯誤500',
  'Error500 Message' => '抱歉，服務器出錯了',
  'Error503' => '錯誤503',
  'Error503 Message' => '抱歉，服務器維護中，請稍後嘗試訪問',
);