<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Picture' => '圖片管理',
  'Account' => '帳號設定',
  'Admin' => '管理員',
  'Catalog' => '產品管理',
  'Category' => '分類',
  'Contact' => '聯絡我們',
  'Dashboard' => '管理首頁',
  'Exit System' => '退出系統',
  'Information' => '單頁訊息',
  'News' => '最新消息',
  'Product' => '產品',
  'Setting' => '網站設定',
  'Asset' => '緩存管理',
  'Site Frontend' => '網站首頁',
  'System' => '系統設定',
);
