<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
	'Setting' => '設置',
	'Update' => '更新',
// meta
	'Meta' => '搜索優化',
	'Meta Title' => '網站名稱',
	'Meta Keywords' => '關鍵詞',
	'Meta Description' => '網站描述',
// mail
	'Mail' => '郵件主機',
	'Mail Email' => '郵箱',
	'Mail Smtp' => '主機',
	'Mail Smtp Host' => '服務器',
	'Mail Smtp User' => '帳號',
	'Mail Smtp Password' => '密碼',
	'Mail Smtp Port' => '端口',
	'Mail Email Contact' => '聯絡郵箱',
// analysis
	'Analysis' => '流量分析',
	'Analysis Google' => 'Google',
);
