<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Super' => '超级',
  'Admin' => '管理员',
  'Admin|Admins' => '管理员',
  'Confirm Password' => '确认密码',
  'Create Time' => '创建时间',
  'Email' => '邮箱',
  'Name' => '姓名',
  'Password' => '密码',
  'Roles' => '管理组',
  'Status' => '启用',
  'Update Time' => '更新时间',
  'Username' => '用户名',
);
