<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Sort Order' => '排序',
  'Code' => '代码',
  'Language' => '语言',
  'Language|Languages' => '语言',
  'Status' => '启用',
  'Title' => '标题',
  '{attribute} can be allowed a-z or \'_\' only, and \'_\' can not be first char and last char.' => '{attribute} 只能是英文小写字母与下划线组合，且下划线不在开头与结尾。',
);
