<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Time' => '',
  'Remark' => '',
  'Status' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => '感谢您的留言，我们将尽速回覆您的留言。',
  'Update Time' => '',
  'Address' => '联络地址',
  'Cellphone' => '市内电话',
  'Company' => '公司',
  'Contact' => '联络我们',
  'Contact|Contacts' => '联络我们',
  'Email' => 'E-Mail',
  'Fax' => '传真号码',
  'Firstname' => '姓氏',
  'Lastname' => '名字',
  'Message' => '留言',
  'Sex' => '称谓',
  'Telephone' => '行动电话',
);
