<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Company' => '公司',
  'Firstname' => '姓氏',
  'Lastname' => '名字',
  'Remark' => '備註',
  'Sex' => '性別',
  'Telephone' => '電話',
  'Address' => '地址',
  'Cellphone' => '手機',
  'Contact' => '聯絡我們',
  'Contact|Contacts' => '聯絡我們',
  'Create Time' => '創建時間',
  'Email' => '電子郵箱',
  'Fax' => '傳真',
  'Message' => '留言',
  'Status' => '狀態',
  'Update Time' => '更新時間',
);
